baseurl: "http://tlog.desiyonan.tech"
title: "DnF's Zone"
defaultContentLanguage: zh-cn
# uglyURLs: true
watch: true
hasCJKLanguage: true
footnotereturnlinkcontents: "↩"
theme: PaperMod
permalinks:
  post: /:year/:month/:slug/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "DnF"
  GitHubUser: "desiyonan"
  SidebarRecentLimit: 5