baseurl: "http://tlog.desiyonan.tech"
title: "DnF's Zone"
languageCode: "zn-cn"
# uglyURLs: true
watch: true
hasCJKLanguage: true
footnotereturnlinkcontents: "↩"
theme: PaperMod
publishdir: docs
permalinks:
  post: /:year/:month/:slug/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "DnF"
  GitHubUser: "desiyonan"
  SidebarRecentLimit: 5